export interface Hotel {
  id: number;
  shortName: string;
  name: string;
  type: string;
  currency: string;
  street: string;
  state: string;
  country: string;
  pincode: string;
  location: string;
  email: string;
  phone: string;
}

export const hotelList: Hotel[] = [
  {
    id: 1,
    shortName: "Taj West End 1",
    name: "Taj West End, Bengaluru 1",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact1@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 2,
    shortName: "The Leela 2",
    name: "The Leela Palace Bengaluru 2",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact2@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 3,
    shortName: "The Oberoi 3",
    name: "The Oberoi, Bengaluru 3",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact3@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 4,
    shortName: "Taj West End 4",
    name: "Taj West End, Bengaluru 4",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact4@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 5,
    shortName: "The Leela 5",
    name: "The Leela Palace Bengaluru 5",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact5@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 6,
    shortName: "The Oberoi 6",
    name: "The Oberoi, Bengaluru 6",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact6@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 7,
    shortName: "Taj West End 7",
    name: "Taj West End, Bengaluru 7",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact7@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 8,
    shortName: "The Leela 8",
    name: "The Leela Palace Bengaluru 8",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact8@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 9,
    shortName: "The Oberoi 9",
    name: "The Oberoi, Bengaluru 9",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact9@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 10,
    shortName: "Taj West End 10",
    name: "Taj West End, Bengaluru 10",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact10@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 11,
    shortName: "The Leela 11",
    name: "The Leela Palace Bengaluru 11",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact11@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 12,
    shortName: "The Oberoi 12",
    name: "The Oberoi, Bengaluru 12",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact12@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 13,
    shortName: "Taj West End 13",
    name: "Taj West End, Bengaluru 13",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact13@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 14,
    shortName: "The Leela 14",
    name: "The Leela Palace Bengaluru 14",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact14@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 15,
    shortName: "The Oberoi 15",
    name: "The Oberoi, Bengaluru 15",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact15@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 16,
    shortName: "Taj West End 16",
    name: "Taj West End, Bengaluru 16",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact16@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 17,
    shortName: "The Leela 17",
    name: "The Leela Palace Bengaluru 17",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact17@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 18,
    shortName: "The Oberoi 18",
    name: "The Oberoi, Bengaluru 18",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact18@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 19,
    shortName: "Taj West End 19",
    name: "Taj West End, Bengaluru 19",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact19@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 20,
    shortName: "The Leela 20",
    name: "The Leela Palace Bengaluru 20",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact20@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 21,
    shortName: "The Oberoi 21",
    name: "The Oberoi, Bengaluru 21",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact21@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 22,
    shortName: "Taj West End 22",
    name: "Taj West End, Bengaluru 22",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact22@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 23,
    shortName: "The Leela 23",
    name: "The Leela Palace Bengaluru 23",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact23@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 24,
    shortName: "The Oberoi 24",
    name: "The Oberoi, Bengaluru 24",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact24@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 25,
    shortName: "Taj West End 25",
    name: "Taj West End, Bengaluru 25",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact25@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 26,
    shortName: "The Leela 26",
    name: "The Leela Palace Bengaluru 26",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact26@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 27,
    shortName: "The Oberoi 27",
    name: "The Oberoi, Bengaluru 27",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact27@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 28,
    shortName: "Taj West End 28",
    name: "Taj West End, Bengaluru 28",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact28@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 29,
    shortName: "The Leela 29",
    name: "The Leela Palace Bengaluru 29",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact29@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 30,
    shortName: "The Oberoi 30",
    name: "The Oberoi, Bengaluru 30",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact30@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 31,
    shortName: "Taj West End 31",
    name: "Taj West End, Bengaluru 31",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact31@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 32,
    shortName: "The Leela 32",
    name: "The Leela Palace Bengaluru 32",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact32@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 33,
    shortName: "The Oberoi 33",
    name: "The Oberoi, Bengaluru 33",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact33@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 34,
    shortName: "Taj West End 34",
    name: "Taj West End, Bengaluru 34",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact34@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 35,
    shortName: "The Leela 35",
    name: "The Leela Palace Bengaluru 35",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact35@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 36,
    shortName: "The Oberoi 36",
    name: "The Oberoi, Bengaluru 36",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact36@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 37,
    shortName: "Taj West End 37",
    name: "Taj West End, Bengaluru 37",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact37@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 38,
    shortName: "The Leela 38",
    name: "The Leela Palace Bengaluru 38",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact38@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 39,
    shortName: "The Oberoi 39",
    name: "The Oberoi, Bengaluru 39",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact39@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 40,
    shortName: "Taj West End 40",
    name: "Taj West End, Bengaluru 40",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact40@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 41,
    shortName: "The Leela 41",
    name: "The Leela Palace Bengaluru 41",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact41@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 42,
    shortName: "The Oberoi 42",
    name: "The Oberoi, Bengaluru 42",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact42@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 43,
    shortName: "Taj West End 43",
    name: "Taj West End, Bengaluru 43",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact43@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 44,
    shortName: "The Leela 44",
    name: "The Leela Palace Bengaluru 44",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact44@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 45,
    shortName: "The Oberoi 45",
    name: "The Oberoi, Bengaluru 45",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact45@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 46,
    shortName: "Taj West End 46",
    name: "Taj West End, Bengaluru 46",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact46@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 47,
    shortName: "The Leela 47",
    name: "The Leela Palace Bengaluru 47",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact47@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 48,
    shortName: "The Oberoi 48",
    name: "The Oberoi, Bengaluru 48",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact48@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 49,
    shortName: "Taj West End 49",
    name: "Taj West End, Bengaluru 49",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact49@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 50,
    shortName: "The Leela 50",
    name: "The Leela Palace Bengaluru 50",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact50@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 51,
    shortName: "The Oberoi 51",
    name: "The Oberoi, Bengaluru 51",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact51@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 52,
    shortName: "Taj West End 52",
    name: "Taj West End, Bengaluru 52",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact52@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 53,
    shortName: "The Leela 53",
    name: "The Leela Palace Bengaluru 53",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact53@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 54,
    shortName: "The Oberoi 54",
    name: "The Oberoi, Bengaluru 54",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact54@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 55,
    shortName: "Taj West End 55",
    name: "Taj West End, Bengaluru 55",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact55@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 56,
    shortName: "The Leela 56",
    name: "The Leela Palace Bengaluru 56",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact56@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 57,
    shortName: "The Oberoi 57",
    name: "The Oberoi, Bengaluru 57",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact57@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 58,
    shortName: "Taj West End 58",
    name: "Taj West End, Bengaluru 58",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact58@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 59,
    shortName: "The Leela 59",
    name: "The Leela Palace Bengaluru 59",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact59@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 60,
    shortName: "The Oberoi 60",
    name: "The Oberoi, Bengaluru 60",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact60@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 61,
    shortName: "Taj West End 61",
    name: "Taj West End, Bengaluru 61",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact61@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 62,
    shortName: "The Leela 62",
    name: "The Leela Palace Bengaluru 62",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact62@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 63,
    shortName: "The Oberoi 63",
    name: "The Oberoi, Bengaluru 63",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact63@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 64,
    shortName: "Taj West End 64",
    name: "Taj West End, Bengaluru 64",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact64@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 65,
    shortName: "The Leela 65",
    name: "The Leela Palace Bengaluru 65",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact65@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 66,
    shortName: "The Oberoi 66",
    name: "The Oberoi, Bengaluru 66",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact66@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 67,
    shortName: "Taj West End 67",
    name: "Taj West End, Bengaluru 67",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact67@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 68,
    shortName: "The Leela 68",
    name: "The Leela Palace Bengaluru 68",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact68@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 69,
    shortName: "The Oberoi 69",
    name: "The Oberoi, Bengaluru 69",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact69@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 70,
    shortName: "Taj West End 70",
    name: "Taj West End, Bengaluru 70",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact70@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 71,
    shortName: "The Leela 71",
    name: "The Leela Palace Bengaluru 71",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact71@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 72,
    shortName: "The Oberoi 72",
    name: "The Oberoi, Bengaluru 72",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact72@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 73,
    shortName: "Taj West End 73",
    name: "Taj West End, Bengaluru 73",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact73@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 74,
    shortName: "The Leela 74",
    name: "The Leela Palace Bengaluru 74",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact74@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 75,
    shortName: "The Oberoi 75",
    name: "The Oberoi, Bengaluru 75",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact75@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 76,
    shortName: "Taj West End 76",
    name: "Taj West End, Bengaluru 76",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact76@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 77,
    shortName: "The Leela 77",
    name: "The Leela Palace Bengaluru 77",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact77@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 78,
    shortName: "The Oberoi 78",
    name: "The Oberoi, Bengaluru 78",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact78@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 79,
    shortName: "Taj West End 79",
    name: "Taj West End, Bengaluru 79",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact79@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 80,
    shortName: "The Leela 80",
    name: "The Leela Palace Bengaluru 80",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact80@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 81,
    shortName: "The Oberoi 81",
    name: "The Oberoi, Bengaluru 81",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact81@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 82,
    shortName: "Taj West End 82",
    name: "Taj West End, Bengaluru 82",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact82@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 83,
    shortName: "The Leela 83",
    name: "The Leela Palace Bengaluru 83",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact83@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 84,
    shortName: "The Oberoi 84",
    name: "The Oberoi, Bengaluru 84",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact84@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 85,
    shortName: "Taj West End 85",
    name: "Taj West End, Bengaluru 85",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact85@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 86,
    shortName: "The Leela 86",
    name: "The Leela Palace Bengaluru 86",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact86@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 87,
    shortName: "The Oberoi 87",
    name: "The Oberoi, Bengaluru 87",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact87@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 88,
    shortName: "Taj West End 88",
    name: "Taj West End, Bengaluru 88",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact88@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 89,
    shortName: "The Leela 89",
    name: "The Leela Palace Bengaluru 89",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact89@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 90,
    shortName: "The Oberoi 90",
    name: "The Oberoi, Bengaluru 90",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact90@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 91,
    shortName: "Taj West End 91",
    name: "Taj West End, Bengaluru 91",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact91@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 92,
    shortName: "The Leela 92",
    name: "The Leela Palace Bengaluru 92",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact92@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 93,
    shortName: "The Oberoi 93",
    name: "The Oberoi, Bengaluru 93",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact93@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 94,
    shortName: "Taj West End 94",
    name: "Taj West End, Bengaluru 94",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact94@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 95,
    shortName: "The Leela 95",
    name: "The Leela Palace Bengaluru 95",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact95@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 96,
    shortName: "The Oberoi 96",
    name: "The Oberoi, Bengaluru 96",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact96@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 97,
    shortName: "Taj West End 97",
    name: "Taj West End, Bengaluru 97",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact97@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 98,
    shortName: "The Leela 98",
    name: "The Leela Palace Bengaluru 98",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact98@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 99,
    shortName: "The Oberoi 99",
    name: "The Oberoi, Bengaluru 99",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact99@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 100,
    shortName: "Taj West End 100",
    name: "Taj West End, Bengaluru 100",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact100@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 101,
    shortName: "The Leela 101",
    name: "The Leela Palace Bengaluru 101",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact101@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 102,
    shortName: "The Oberoi 102",
    name: "The Oberoi, Bengaluru 102",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact102@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 103,
    shortName: "Taj West End 103",
    name: "Taj West End, Bengaluru 103",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact103@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 104,
    shortName: "The Leela 104",
    name: "The Leela Palace Bengaluru 104",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact104@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 105,
    shortName: "The Oberoi 105",
    name: "The Oberoi, Bengaluru 105",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact105@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 106,
    shortName: "Taj West End 106",
    name: "Taj West End, Bengaluru 106",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact106@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 107,
    shortName: "The Leela 107",
    name: "The Leela Palace Bengaluru 107",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact107@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 108,
    shortName: "The Oberoi 108",
    name: "The Oberoi, Bengaluru 108",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact108@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 109,
    shortName: "Taj West End 109",
    name: "Taj West End, Bengaluru 109",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact109@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 110,
    shortName: "The Leela 110",
    name: "The Leela Palace Bengaluru 110",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact110@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 111,
    shortName: "The Oberoi 111",
    name: "The Oberoi, Bengaluru 111",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact111@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 112,
    shortName: "Taj West End 112",
    name: "Taj West End, Bengaluru 112",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact112@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 113,
    shortName: "The Leela 113",
    name: "The Leela Palace Bengaluru 113",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact113@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 114,
    shortName: "The Oberoi 114",
    name: "The Oberoi, Bengaluru 114",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact114@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 115,
    shortName: "Taj West End 115",
    name: "Taj West End, Bengaluru 115",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact115@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 116,
    shortName: "The Leela 116",
    name: "The Leela Palace Bengaluru 116",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact116@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 117,
    shortName: "The Oberoi 117",
    name: "The Oberoi, Bengaluru 117",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact117@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 118,
    shortName: "Taj West End 118",
    name: "Taj West End, Bengaluru 118",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact118@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 119,
    shortName: "The Leela 119",
    name: "The Leela Palace Bengaluru 119",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact119@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 120,
    shortName: "The Oberoi 120",
    name: "The Oberoi, Bengaluru 120",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact120@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 121,
    shortName: "Taj West End 121",
    name: "Taj West End, Bengaluru 121",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact121@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 122,
    shortName: "The Leela 122",
    name: "The Leela Palace Bengaluru 122",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact122@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 123,
    shortName: "The Oberoi 123",
    name: "The Oberoi, Bengaluru 123",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact123@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 124,
    shortName: "Taj West End 124",
    name: "Taj West End, Bengaluru 124",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact124@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 125,
    shortName: "The Leela 125",
    name: "The Leela Palace Bengaluru 125",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact125@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 126,
    shortName: "The Oberoi 126",
    name: "The Oberoi, Bengaluru 126",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact126@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 127,
    shortName: "Taj West End 127",
    name: "Taj West End, Bengaluru 127",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact127@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 128,
    shortName: "The Leela 128",
    name: "The Leela Palace Bengaluru 128",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact128@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 129,
    shortName: "The Oberoi 129",
    name: "The Oberoi, Bengaluru 129",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact129@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 130,
    shortName: "Taj West End 130",
    name: "Taj West End, Bengaluru 130",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact130@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 131,
    shortName: "The Leela 131",
    name: "The Leela Palace Bengaluru 131",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact131@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 132,
    shortName: "The Oberoi 132",
    name: "The Oberoi, Bengaluru 132",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact132@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 133,
    shortName: "Taj West End 133",
    name: "Taj West End, Bengaluru 133",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact133@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 134,
    shortName: "The Leela 134",
    name: "The Leela Palace Bengaluru 134",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact134@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 135,
    shortName: "The Oberoi 135",
    name: "The Oberoi, Bengaluru 135",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact135@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 136,
    shortName: "Taj West End 136",
    name: "Taj West End, Bengaluru 136",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact136@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 137,
    shortName: "The Leela 137",
    name: "The Leela Palace Bengaluru 137",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact137@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 138,
    shortName: "The Oberoi 138",
    name: "The Oberoi, Bengaluru 138",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact138@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 139,
    shortName: "Taj West End 139",
    name: "Taj West End, Bengaluru 139",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact139@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 140,
    shortName: "The Leela 140",
    name: "The Leela Palace Bengaluru 140",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact140@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 141,
    shortName: "The Oberoi 141",
    name: "The Oberoi, Bengaluru 141",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact141@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 142,
    shortName: "Taj West End 142",
    name: "Taj West End, Bengaluru 142",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact142@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 143,
    shortName: "The Leela 143",
    name: "The Leela Palace Bengaluru 143",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact143@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 144,
    shortName: "The Oberoi 144",
    name: "The Oberoi, Bengaluru 144",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact144@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 145,
    shortName: "Taj West End 145",
    name: "Taj West End, Bengaluru 145",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact145@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 146,
    shortName: "The Leela 146",
    name: "The Leela Palace Bengaluru 146",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact146@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 147,
    shortName: "The Oberoi 147",
    name: "The Oberoi, Bengaluru 147",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact147@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 148,
    shortName: "Taj West End 148",
    name: "Taj West End, Bengaluru 148",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact148@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 149,
    shortName: "The Leela 149",
    name: "The Leela Palace Bengaluru 149",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact149@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 150,
    shortName: "The Oberoi 150",
    name: "The Oberoi, Bengaluru 150",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact150@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 151,
    shortName: "Taj West End 151",
    name: "Taj West End, Bengaluru 151",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact151@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 152,
    shortName: "The Leela 152",
    name: "The Leela Palace Bengaluru 152",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact152@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 153,
    shortName: "The Oberoi 153",
    name: "The Oberoi, Bengaluru 153",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact153@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 154,
    shortName: "Taj West End 154",
    name: "Taj West End, Bengaluru 154",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact154@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 155,
    shortName: "The Leela 155",
    name: "The Leela Palace Bengaluru 155",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact155@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 156,
    shortName: "The Oberoi 156",
    name: "The Oberoi, Bengaluru 156",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact156@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 157,
    shortName: "Taj West End 157",
    name: "Taj West End, Bengaluru 157",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact157@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 158,
    shortName: "The Leela 158",
    name: "The Leela Palace Bengaluru 158",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact158@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 159,
    shortName: "The Oberoi 159",
    name: "The Oberoi, Bengaluru 159",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact159@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 160,
    shortName: "Taj West End 160",
    name: "Taj West End, Bengaluru 160",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact160@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 161,
    shortName: "The Leela 161",
    name: "The Leela Palace Bengaluru 161",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact161@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 162,
    shortName: "The Oberoi 162",
    name: "The Oberoi, Bengaluru 162",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact162@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 163,
    shortName: "Taj West End 163",
    name: "Taj West End, Bengaluru 163",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact163@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 164,
    shortName: "The Leela 164",
    name: "The Leela Palace Bengaluru 164",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact164@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 165,
    shortName: "The Oberoi 165",
    name: "The Oberoi, Bengaluru 165",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact165@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 166,
    shortName: "Taj West End 166",
    name: "Taj West End, Bengaluru 166",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact166@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 167,
    shortName: "The Leela 167",
    name: "The Leela Palace Bengaluru 167",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact167@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 168,
    shortName: "The Oberoi 168",
    name: "The Oberoi, Bengaluru 168",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact168@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 169,
    shortName: "Taj West End 169",
    name: "Taj West End, Bengaluru 169",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact169@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 170,
    shortName: "The Leela 170",
    name: "The Leela Palace Bengaluru 170",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact170@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 171,
    shortName: "The Oberoi 171",
    name: "The Oberoi, Bengaluru 171",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact171@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 172,
    shortName: "Taj West End 172",
    name: "Taj West End, Bengaluru 172",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact172@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 173,
    shortName: "The Leela 173",
    name: "The Leela Palace Bengaluru 173",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact173@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 174,
    shortName: "The Oberoi 174",
    name: "The Oberoi, Bengaluru 174",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact174@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 175,
    shortName: "Taj West End 175",
    name: "Taj West End, Bengaluru 175",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact175@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 176,
    shortName: "The Leela 176",
    name: "The Leela Palace Bengaluru 176",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact176@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 177,
    shortName: "The Oberoi 177",
    name: "The Oberoi, Bengaluru 177",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact177@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 178,
    shortName: "Taj West End 178",
    name: "Taj West End, Bengaluru 178",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact178@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 179,
    shortName: "The Leela 179",
    name: "The Leela Palace Bengaluru 179",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact179@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 180,
    shortName: "The Oberoi 180",
    name: "The Oberoi, Bengaluru 180",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact180@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 181,
    shortName: "Taj West End 181",
    name: "Taj West End, Bengaluru 181",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact181@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 182,
    shortName: "The Leela 182",
    name: "The Leela Palace Bengaluru 182",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact182@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 183,
    shortName: "The Oberoi 183",
    name: "The Oberoi, Bengaluru 183",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact183@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 184,
    shortName: "Taj West End 184",
    name: "Taj West End, Bengaluru 184",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact184@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 185,
    shortName: "The Leela 185",
    name: "The Leela Palace Bengaluru 185",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact185@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 186,
    shortName: "The Oberoi 186",
    name: "The Oberoi, Bengaluru 186",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact186@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 187,
    shortName: "Taj West End 187",
    name: "Taj West End, Bengaluru 187",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact187@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 188,
    shortName: "The Leela 188",
    name: "The Leela Palace Bengaluru 188",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact188@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 189,
    shortName: "The Oberoi 189",
    name: "The Oberoi, Bengaluru 189",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact189@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 190,
    shortName: "Taj West End 190",
    name: "Taj West End, Bengaluru 190",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact190@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 191,
    shortName: "The Leela 191",
    name: "The Leela Palace Bengaluru 191",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact191@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 192,
    shortName: "The Oberoi 192",
    name: "The Oberoi, Bengaluru 192",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact192@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 193,
    shortName: "Taj West End 193",
    name: "Taj West End, Bengaluru 193",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact193@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 194,
    shortName: "The Leela 194",
    name: "The Leela Palace Bengaluru 194",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact194@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 195,
    shortName: "The Oberoi 195",
    name: "The Oberoi, Bengaluru 195",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact195@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 196,
    shortName: "Taj West End 196",
    name: "Taj West End, Bengaluru 196",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact196@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 197,
    shortName: "The Leela 197",
    name: "The Leela Palace Bengaluru 197",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact197@example.com",
    phone: "+91 80 2521 1234"
  },
  {
    id: 198,
    shortName: "The Oberoi 198",
    name: "The Oberoi, Bengaluru 198",
    type: "Luxury",
    currency: "INR",
    street: "39, Mahatma Gandhi Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "39, Mahatma Gandhi Road, Karnataka, India - 560001",
    email: "contact198@example.com",
    phone: "+91 80 2558 5858"
  },
  {
    id: 199,
    shortName: "Taj West End 199",
    name: "Taj West End, Bengaluru 199",
    type: "Luxury",
    currency: "INR",
    street: "25, Race Course Road",
    state: "Karnataka",
    country: "India",
    pincode: "560001",
    location: "25, Race Course Road, Karnataka, India - 560001",
    email: "contact199@example.com",
    phone: "+91 80 6660 5660"
  },
  {
    id: 200,
    shortName: "The Leela 200",
    name: "The Leela Palace Bengaluru 200",
    type: "Luxury",
    currency: "INR",
    street: "23, HAL Old Airport Road",
    state: "Karnataka",
    country: "India",
    pincode: "560008",
    location: "23, HAL Old Airport Road, Karnataka, India - 560008",
    email: "contact200@example.com",
    phone: "+91 80 2521 1234"
  }
];



// export const hotelsList = [
//     "The Oberoi, Bengaluru",
//     "Taj West End",
//     "The Ritz-Carlton, Bangalore",
//     "JW Marriott Hotel Bengaluru",
//     "Four Seasons Hotel Bengaluru at Embassy ONE",
//     "Conrad Bengaluru",
//     "The Leela Palace Bengaluru",
//     "ITC Gardenia, a Luxury Collection Hotel",
//     "Shangri-La Hotel, Bengaluru",
//     "Sheraton Grand Bangalore Hotel at Brigade Gateway",
//     "Taj MG Road, Bengaluru",
//     "ITC Windsor, a Luxury Collection Hotel",
//     "Bengaluru Marriott Hotel Whitefield",
//     "Hilton Bangalore Embassy GolfLinks",
//     "Grand Mercure Bangalore",
//     "Radisson Blu Atria Bengaluru",
//     "DoubleTree Suites by Hilton Bengaluru",
//     "Aloft Bengaluru Cessna Business Park",
//     "The Paul Bangalore",
//     "Oakwood Premier Prestige Bangalore",
//     "Fairfield by Marriott Bengaluru Rajajinagar",
//     "Holiday Inn Express Bengaluru Yeshwantpur",
//     "Courtyard by Marriott Bengaluru Outer Ring Road",
//     "Hyatt Centric MG Road Bangalore",
//     "Lemon Tree Premier, Ulsoor Lake",
//     "Keys Select Hotel Whitefield",
//     "Fortune Select JP Cosmos",
//     "ibis Bengaluru City Centre",
//     "The Chancery Pavilion",
//     "Sterlings Mac Hotel",
//     "Casa Cottage",
//     "Laika Boutique Stay",
//     "The Green Path Eco Hotel",
//     "The Courtyard",
//     "The Bougain Villa",
//     "Jayamahal Palace Hotel",
//     "The Park Bangalore",
//     "The HHI Select Bengaluru",
//     "The Elanza Hotel",
//     "The Monarch Luxur",
//     "Treebo Trend Raj Premier",
//     "FabHotel Astra Suites",
//     "OYO Townhouse 011 Esplanade",
//     "Hotel Nandhini Jayanagar",
//     "Hotel City Centaur",
//     "Hotel TAP Gold Crest",
//     "Hotel Empire International",
//     "Hotel Swagath",
//     "Hotel Pai Viceroy",
//     "Hotel Chalukya",
//     "Aloft Bengaluru Outer Ring Road Hotel",
//     "Ananya Comfortss - Koramangala Hotel Bangalore",
//     "Blvd Club - Near Bengaluru Airport Hotel Settahalasur",
//     "Brahmi Resort Dod Ballapur",
//     "Clarks Exotica Convention Resort & Spa Devanahalli",
//     "Courtyard By Marriott Bengaluru Hebbal Hotel",
//     "Crown Inn Bangalore",
//     "Fortune Select JP Cosmos, Bengaluru - Member ITC Hotels' Group",
//     "Gokulam Grand Hotel & Spa Bangalore",
//     "Grand Mercure Bengaluru At Gopalan Mall - An Accor Brand",
//     "Greenpark Bengaluru",
//     "Hilton Bengaluru Embassy Manyata Business Park Hotel",
//     "Holiday Inn Bengaluru Racecourse By IHG",
//     "Hotel Prince Palace",
//     "Hotel Royal Orchid Bangalore",
//     "Hyatt Centric MG Road Bangalore",
//     "Ista Hotel Bangalore",
//     "JW Marriott Hotel Bengaluru Prestige Golfshire Resort & Spa Avati",
//     "Kshemavana The Wellness Retreat Bangalore",
//     "La Marvella, Bengaluru Hotel",
//     "Le Meridien Bangalore",
//     "Lemon Tree Premier, Ulsoor Lake, Bengaluru",
//     "Mount City Park Hotel Madiwala Bangalore",
//     "Mulberry Shades Bengaluru Nandi Hills - A Tribute Portfolio Resort Nandigunda",
//     "Novotel Bengaluru Outer Ring Road",
//     "Oakwood Residence Whitefield Bangalore",
//     "Palm Meadows Resort Bangalore",
//     "Pride Image Hotel Bangalore",
//     "Radisson Blu Bengaluru Outer Ring Road Hotel",
//     "Ramada By Wyndham Bengaluru Yelahanka",
//     "Renaissance Bengaluru Race Course Hotel",
//     "Royal Stay Bangalore",
//     "S K Residency Hotel Bangalore",
//     "Sheraton Grand Bengaluru Whitefield Hotel & Convention Center",
//     "Shreyas Retreat Hotel Nelamangala",
//     "Sterlings Mac Hotel Bangalore",
//     "Svenska Design Hotel, Electronic City, Bangalore",
//     "Taj Bangalore Devanahalli",
//     "Taj Yeshwantpur Bengaluru Hotel",
//     "The Den, Bengaluru Hotel",
//     "The Elite Narasapura, A Member Of Radisson Individuals Hotel",
//     "The Golden Palms Hotel & Spa Chik Banavar",
//     "The Lalit Ashok Hotel Bangalore",
//     "The Leela Bhartiya City Bengaluru",
//     "The Oterra Hotel Bangalore",
//     "The Zuri Whitefield Bengaluru Hotel",
//     "Vivanta Bengaluru Residency Road",
//     "Vivanta Bengaluru, Whitefield",
//     "Vividus Hotel Bangalore",
//     "Welcomhotel By ITC Hotels, Richmond Road, Bengaluru",
//     "Westernsuites Hotel / Spa Bangalore",
//   ];
  